// Deprecated: ID3 Tag scanning, parsing, and caching have been moved entirely to the Node.js server (server.js).
// The client receives pre-parsed track metadata via /api/tracks, cover art via /api/cover?id=..., and lyrics on demand via /api/lyrics?id=...
